### ISSUE TITLE
如果用x11写一套虚拟桌面系统，会不会更有意思

### ISSUE THREAD

**Issue by naaive** [vprix/vncproxy#1]
类似vnc这种framebuffer协议相当于开了个远程桌面，无法做到计算与UI分离

**Comment by osgochina** [comment]
一步一步来，一口吃不成大胖子哈，先满足基础要求再说

**Comment by beordle** [comment]
我感觉这项目主要是中间人场景。你们的讨论是啥背景？听不太懂...（是有啥群吗）

**Comment by beordle** [comment]
https://v2ex.com/t/858727#reply12 原来是这里！找到了
