### ISSUE TITLE
wsServer启动成功，但是不能访问，请问啥原因呢

### ISSUE THREAD

**Issue by MaoSkin** [vprix/vncproxy#3]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/28040945/177001515-62ae5390-3b06-4651-9ab3-d64849c983c3.png">

**Comment by osgochina** [comment]
我看的你截图，一直出错在权限认证阶段，从参数上看并没有使用 proxyPassword这个参数，说明没有设置代理的密码，
那么你使用novnc连接的时候，密码参数需要置空，不然novnc会进行密码认证流程。
![image](https://user-images.githubusercontent.com/1379073/177071021-94e5e1db-a4c3-4af0-b4e8-bef095dc8948.png)
