### ISSUE TITLE
无法识别host

### ISSUE THREAD

**Issue by tangjpA1** [vprix/vncproxy#6]
./proxy start tcpServer --vncHost=10.113.6.94   --vncPort=5901  --vncPassword=123456  --proxyPassword=123456  --debug --pid=/tmp/server.pid
2023-07-18 18:32:46.020 22929: 服务已经初始化完成, 10 个协程被创建.
2023-07-18 18:32:46.039 [FATA] Error listen. listen tcp: lookup "0.0.0.0": no such host
Stack:
1.  main.(*TcpSandBox).Setup
    /tangjp/go_study/vncproxy/cmd/proxy/tcpServer.go:58
2.  github.com/osgochina/dmicro/easyservice.(*EasyService).Setup.func1.1
    /root/go/pkg/mod/github.com/osgochina/dmicro@v1.2.1/easyservice/service.go:104

**Comment by osgochina** [comment]
你的参数少,加上tcpHost,tcpPort

**Comment by tangjpA1** [comment]
./proxy start tcpServer --vncHost=10.113.6.94   --vncPort=5901  --vncPassword=123456  --tcpHost=10.113.6.94  --tcpPort=8989  --proxyPassword=123456  --debug 
2023-07-18 18:40:43.491 23263: 服务已经初始化完成, 10 个协程被创建.
2023-07-18 18:40:43.495 [FATA] Error listen. listen tcp: lookup "10.113.6.94": no such host
Stack:
1.  main.(*TcpSandBox).Setup
    /tangjp/go_study/vncproxy/cmd/proxy/tcpServer.go:58
2.  github.com/osgochina/dmicro/easyservice.(*EasyService).Setup.func1.1
    /root/go/pkg/mod/github.com/osgochina/dmicro@v1.2.1/easyservice/service.go:104  我之前就是加了不对，如果不添加这两个参数说明说是默认的。我这里再次拿出来看看，确实不对呢

**Comment by tangjpA1** [comment]
> 你的参数少,加上tcpHost,tcpPort

OPTION
	--vncHost       要连接的vnc服务端地址  必传
	--vncPort       要连接的vnc服务端端口 必传
	--vncPassword   要连接的vnc服务端密码 不传则使用auth none
	--tcpHost       本地监听的tcp协议地址 默认0.0.0.0
	--tcpPort       本地监听的tcp协议端口 默认8989
	--proxyPassword 连接到proxy的密码   不传入密码则使用auth none
	--wsHost        启动websocket服务的本地地址  默认 0.0.0.0
	--wsPort        启动websocket服务的本地端口 默认8988
	--wsPath        启动websocket服务的url path 默认'/'
	--debug         是否开启debug 默认debug=false
	-d,--daemon     使用守护进程模式启动
	--pid           设置pid文件的地址，默认是/tmp/[server].pid
	-h,--help       获取帮助信息
	-v,--version    获取编译版本信息

**Comment by osgochina** [comment]
已修复
